### ISSUE TITLE
Error trying to run overview and demo examples

### ISSUE THREAD

**Issue by JustKatie** [aarzilli/nucular#17]
Go compiles successfully the overview and demo examples, but when I try to run the binaries I get error. I have no problem running the simple example.

Here the output of the console when trying to run overview.exe:

> overview.exe
> Exception 0xc000001d 0x0 0x0 0x52ed6c
> PC=0x52ed6c
> 
> github.com/aarzilli/nucular.drawFillOver_SIMD_internal(0x4a17e1c, 0x80dc, 0x81e8, 0x1200, 0x1f, 0x30300000000a, 0x6f6f00005353)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/drawfillover_amd64.s:37 +0x1c
> github.com/aarzilli/nucular.drawFillOver(0xc0000340c0, 0xbe, 0xe, 0x101, 0x2d, 0x535300003030, 0xf5f500006f6f)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/drawfillover_amd64.go:13 +0xdb
> github.com/aarzilli/nucular.drawFill(0xc0000340c0, 0xbe, 0xe, 0x101, 0x2d, 0xc00001a0a0, 0xbe, 0xe, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/context.go:999 +0x1f5
> github.com/aarzilli/nucular.(*context).Draw(0xc00009c000, 0xc00018e020, 0x2b)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/context.go:445 +0xdc8
> github.com/aarzilli/nucular.(*masterWindow).draw(0xc0000a2000, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:487 +0x179
> github.com/aarzilli/nucular.(*masterWindow).updateLocked(0xc0000a2000)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:379 +0x220
> github.com/aarzilli/nucular.(*masterWindow).handleEventLocked(0xc0000a2000, 0x5730c0, 0xc00004618c, 0xc000186001)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:188 +0x24b
> github.com/aarzilli/nucular.(*masterWindow).main(0xc0000a2000, 0x5c9020, 0x6d8f00)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:172 +0x230
> github.com/aarzilli/nucular.(*masterWindow).main-fm(0x5c9020, 0x6d8f00)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:128 +0x45
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver.Main.func1()
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver/windriver.go:22 +0x44
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32.screenWindowWndProc.func1()
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/win32.go:298 +0x30
> created by github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32.screenWindowWndProc
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/win32.go:297 +0x123
> 
> goroutine 1 [syscall, locked to thread]:
> syscall.Syscall6(0x7ffe398d1ae0, 0x4, 0xc00006be70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Go/src/runtime/syscall_windows.go:185 +0xfc
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32._GetMessage(0xc00006be70, 0x0, 0x0, 0x1, 0x0, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/zsyscall_windows.go:184 +0x90
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32.Main(0xc00003a440, 0x0, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/win32.go:479 +0x122
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver.Main(0xc00003a430)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver/windriver.go:22 +0x62
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver.main(0xc00003a430)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/driver_windows.go:13 +0x32
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver.Main(0xc00003a430)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/driver.go:24 +0x32
> github.com/aarzilli/nucular.(*masterWindow).Main(0xc0000a2000)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:128 +0x5e
> main.main()
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/_examples/overview/main.go:40 +0x11b
> 
> goroutine 4 [semacquire]:
> sync.runtime_SemacquireMutex(0xc0000a22a4, 0xc00017ff00)
>         C:/Go/src/runtime/sema.go:71 +0x44
> sync.(*Mutex).Lock(0xc0000a22a0)
>         C:/Go/src/sync/mutex.go:134 +0x106
> github.com/aarzilli/nucular.(*masterWindow).updater.func1(0xc0000a2000, 0xc00017ffc7)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:329 +0x55
> github.com/aarzilli/nucular.(*masterWindow).updater(0xc0000a2000)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:349 +0x43
> created by github.com/aarzilli/nucular.(*masterWindow).main
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:167 +0x1b7
> rax     0xf5f5
> rbx     0x1200
> rcx     0x6f6f
> rdi     0xe
> rsi     0x80dc
> rbp     0xc00005f828
> rsp     0xc00005f7e0
> r8      0x81e8
> r9      0x4a17e1c
> r10     0xbe
> r11     0xc00005f8d0
> r12     0xbe
> r13     0xe
> r14     0x80dc
> r15     0x81e8
> rip     0x52ed6c
> rflags  0x10216
> cs      0x33
> fs      0x53
> gs      0x2b

And the output when trying to run demo.exe:

> demo.exe
> Exception 0xc000001d 0x0 0x0 0x53a53c
> PC=0x53a53c
> 
> github.com/aarzilli/nucular.drawFillOver_SIMD_internal(0x4b20000, 0x360c, 0x3c34, 0x1200, 0x25, 0x333300000023, 0x383800003333)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/drawfillover_amd64.s:37 +0x1c
> github.com/aarzilli/nucular.drawFillOver(0xc000034100, 0x3, 0x3, 0x18d, 0x28, 0x333300003333, 0xdcdc00003838)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/drawfillover_amd64.go:13 +0xdb
> github.com/aarzilli/nucular.drawFill(0xc000034100, 0x3, 0x3, 0x18d, 0x28, 0xc00001a050, 0x3, 0x3, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/context.go:999 +0x1f5
> github.com/aarzilli/nucular.(*context).Draw(0xc000090000, 0xc000184020, 0x1d)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/context.go:445 +0xdc8
> github.com/aarzilli/nucular.(*masterWindow).draw(0xc000096000, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:487 +0x179
> github.com/aarzilli/nucular.(*masterWindow).updateLocked(0xc000096000)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:379 +0x220
> github.com/aarzilli/nucular.(*masterWindow).handleEventLocked(0xc000096000, 0x588920, 0xc0000460da, 0xc00017e001)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:188 +0x24b
> github.com/aarzilli/nucular.(*masterWindow).main(0xc000096000, 0x5e2c80, 0x6ff320)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:172 +0x230
> github.com/aarzilli/nucular.(*masterWindow).main-fm(0x5e2c80, 0x6ff320)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:128 +0x45
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver.Main.func1()
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver/windriver.go:22 +0x44
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32.screenWindowWndProc.func1()
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/win32.go:298 +0x30
> created by github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32.screenWindowWndProc
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/win32.go:297 +0x123
> 
> goroutine 1 [syscall, locked to thread]:
> syscall.Syscall6(0x7ffe398d1ae0, 0x4, 0xc00006bdf8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         C:/Go/src/runtime/syscall_windows.go:185 +0xfc
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32._GetMessage(0xc00006bdf8, 0x0, 0x0, 0x1, 0x0, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/zsyscall_windows.go:184 +0x90
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32.Main(0xc00003a460, 0x0, 0x0)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/internal/win32/win32.go:479 +0x122
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver.Main(0xc00003a450)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/windriver/windriver.go:22 +0x62
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver.main(0xc00003a450)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/driver_windows.go:13 +0x32
> github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver.Main(0xc00003a450)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/vendor/golang.org/x/exp/shiny/driver/driver.go:24 +0x32
> github.com/aarzilli/nucular.(*masterWindow).Main(0xc000096000)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:128 +0x5e
> main.main()
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/_examples/demo/demo.go:124 +0x3de
> 
> goroutine 4 [semacquire]:
> sync.runtime_SemacquireMutex(0xc0000962a4, 0xc000127f00)
>         C:/Go/src/runtime/sema.go:71 +0x44
> sync.(*Mutex).Lock(0xc0000962a0)
>         C:/Go/src/sync/mutex.go:134 +0x106
> github.com/aarzilli/nucular.(*masterWindow).updater.func1(0xc000096000, 0xc000127fc7)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:329 +0x55
> github.com/aarzilli/nucular.(*masterWindow).updater(0xc000096000)
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:349 +0x43
> created by github.com/aarzilli/nucular.(*masterWindow).main
>         C:/Users/Katie/go/src/github.com/aarzilli/nucular/shiny.go:167 +0x1b7
> rax     0xdcdc
> rbx     0x1200
> rcx     0x3838
> rdi     0x3
> rsi     0x360c
> rbp     0xc00005f828
> rsp     0xc00005f7e0
> r8      0x3c34
> r9      0x4b20000
> r10     0x3
> r11     0xc00005f8d0
> r12     0x3
> r13     0x3
> r14     0x360c
> r15     0x3c34
> rip     0x53a53c
> rflags  0x10202
> cs      0x33
> fs      0x53
> gs      0x2b

I'm using windows 10, 64 bits.

**Comment by aarzilli** [comment]
I've pushed a commit that might fix this, can you try again?

**Comment by JustKatie** [comment]
The problem persists, with the same error message in both cases.

**Comment by aarzilli** [comment]
That's very strange. I've pushed another commit that I'd like you to try. But before you compile open `nucular/drawfillover_amd64.go` and change the line that says:

```
const debugUseSIMD = false
```

to:

```
const debugUseSIMD = true
```

I need to figure out which cpu feature I'm using that your cpu is missing. Thank you.

**Comment by JustKatie** [comment]
Now they're working without any problem, them both, demo and overview. With debugUseSIMD set to true the console outputs the following lines:

> useSIMD check
> EAX = 0x01 -> EDX = 0xbfebfbff ECX = 0xc08e39d
> can not use SIMD, no AVX1

Thank you very much.

**Comment by aarzilli** [comment]
Thanks for testing this.
